### ISSUE TITLE
Aggiornamento query sul grafico

### ISSUE THREAD

**Issue by vittoriosantagiuliana** [VRAM-Software/grafana_prediction_plugin#45]
Al cambiamento dell'alias della prima fonte dati il grafico sparisce (solo se il cambiamento avviene successivamente alla selezione del pannello VRAM Software).

La mia comprensione del problema: quando viene selezionato il pannello di tipo plug-in, viene preso l'alias della prima fonte dati e passato a plotly, ma eventuali aggiornamenti dell'alias non sono stati gestiti.

**Comment by marcodallalibera** [comment]
Li dovrebbe gestire l'implementazione della libreria Plotly che per noi è libreria stessa e quindi blackbox. Direi che non lo sistemiamo, semmai aggiorneremo la libreria in futuro se sistemeranno questo bug. Ad oggi in ogni caso ti segnala l'errore ed è abbastanza esplicito capire come risolvere quindi anche per gli utenti non dovrebbe essere un problema. 

Inoltre, se noti, variando l'alias anche la nodeMap è da reimpostare perché perde il riferimento.
