### ISSUE TITLE
Refactoring implementazione plotly

### ISSUE THREAD

**Issue by marcoDallas** [VRAM-Software/grafana_prediction_plugin#7]
Effettuare un refactoring dell'implementazione di plotly così da separare maggiormente le classi fra di loro e la vista dal controllore.

**Comment by marcodallalibera** [comment]
Parzialmente eseguita, rimangono da estrarre tutti i metodi di utilità in una classe apposita. Possibilmente implementare le nostre funzioni angularjs in una classe apposita.
